__title__ = "torchvideo2"
__description__ = "PyTorch video dataset library forked from torchvideo"
__url__ = "https://github.com/DaniNem/torchvideo"
__version__ = "0.0.3"
__author_email__ = "will.price94+torchvideo@gmail.com"
__author__ = "Will Price"
__license__ = "Mozilla Public License 2.0"
__copyright__ = "Copyright 2019 Will Price"
